In [1]:
import pandas as pd

In [2]:
churn = pd.read_csv("churn.csv")
churn.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [3]:
def ChuyenDoi():
    list = ['Account Length','Day Mins','Day Calls','Eve Mins','Eve Calls','Night Mins','Night Calls','Intl Mins','Intl Calls']
    for attribute in list:
        a = churn[attribute].quantile([.25, .5, .75])
        count = 0
        for key in churn[attribute]:
            if key < a[0.25]:
                churn.at[count,attribute]= 1
            elif key < a[0.75]:
                 churn.at[count,attribute]= 2
            else:
                churn.at[count,attribute]= 3
            count += 1

In [4]:
ChuyenDoi()
churn.to_csv('churn_process.csv',index=False) #chuyển đổi các giá trị 4 thuộc tính thành các mức phân vị.

In [6]:
def DeleteRowFalseInChurn():
    count = 0
    for key in churn['Churn?']:
        if key == 'False.':
            churn.drop(count,inplace= True)
        count += 1

In [7]:
DeleteRowFalseInChurn()
churn.to_csv('churn_True.csv',index=False) #Xóa các dòng giá trị False.trong thuộc tính Churn.

In [9]:
churn = pd.read_csv("churn.csv")
def DeleteRowTwoValueNo():
    ChuyenDoi()
    for index in range(churn.shape[0]):
        if churn['VMail Plan'][index] == 'no' and churn["Int'l Plan"][index] == 'no':
            churn.drop(index,inplace = True)

In [10]:
DeleteRowTwoValueNo()
churn.to_csv('churn_plan.csv',index=False) #Xóa các dòng Int'l Plan = no và Vmail plan = no.